console.log('')
console.log('The setup script has moved to a separate CLI package.')
console.log('Use: pnpm create payload-canvas (or npx create-payload-canvas)')
console.log('')
console.log('See: https://github.com/jon8800/payload-canvas')
console.log('')
process.exit(0)
